/**
 * Expanded Meditation Library - 100+ Sessions
 * All YouTube video URLs should be verified working
 * Categories: Breathing, Mindfulness, Visualization, Stress Relief, Sleep
 */

export interface MeditationData {
  id: string
  title: string
  description: string
  type: 'breathing' | 'mindfulness' | 'visualization' | 'stress_relief' | 'sleep'
  duration: number
  videoUrl: string
  level: 'beginner' | 'intermediate' | 'advanced'
  views?: string
  popularity?: number
  instructor?: string
  tags?: string[]
}

export type MeditationType = 'breathing' | 'mindfulness' | 'visualization' | 'stress_relief' | 'sleep'
export type MeditationLevel = 'beginner' | 'intermediate' | 'advanced'

// ============================================
// BREATHING MEDITATIONS (25 sessions)
// ============================================
export const breathingMeditations: MeditationData[] = [
  {
    id: 'br-1',
    title: '5-Minute Meditation You Can Do Anywhere',
    description: 'Quick and effective breathing meditation for busy schedules',
    type: 'breathing',
    duration: 5,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=inpok4MKVLM',
    views: '50M+',
    popularity: 1,
    instructor: 'Goodful',
    tags: ['quick', 'anywhere', 'beginner-friendly']
  },
  {
    id: 'br-2',
    title: 'Deep Breathing Exercise',
    description: 'Calm your mind with this deep breathing practice',
    type: 'breathing',
    duration: 10,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=lS0kcSNlULw',
    views: '40M+',
    popularity: 2,
    instructor: 'Headspace',
    tags: ['deep breathing', 'relaxation', 'calm']
  },
  {
    id: 'br-3',
    title: 'Box Breathing - Navy SEAL Technique',
    description: 'Military-grade breathing technique to reduce stress and anxiety',
    type: 'breathing',
    duration: 5,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=GZzhk9jEkkI',
    views: '35M+',
    popularity: 3,
    instructor: 'Mark Divine',
    tags: ['box breathing', 'navy seal', 'stress relief']
  },
  {
    id: 'br-4',
    title: 'Wim Hof Breathing Tutorial',
    description: 'The famous Iceman breathing method for energy and focus',
    type: 'breathing',
    duration: 11,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=0BNejY1e9ik',
    views: '42M+',
    popularity: 4,
    instructor: 'Wim Hof',
    tags: ['wim hof', 'energy', 'cold therapy']
  },
  {
    id: 'br-5',
    title: '4-7-8 Breathing Technique',
    description: 'Dr. Andrew Weil\'s relaxing breath for sleep and anxiety',
    type: 'breathing',
    duration: 6,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=1Dv-ldGLnIY',
    views: '15M+',
    popularity: 5,
    instructor: 'Dr. Andrew Weil',
    tags: ['4-7-8', 'sleep', 'anxiety relief']
  },
  {
    id: 'br-6',
    title: 'Pranayama for Beginners',
    description: 'Introduction to yogic breathing techniques',
    type: 'breathing',
    duration: 15,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=4uNdlGcySLQ',
    views: '8M+',
    popularity: 6,
    instructor: 'Yoga With Adriene',
    tags: ['pranayama', 'yoga', 'breath control']
  },
  {
    id: 'br-7',
    title: 'Alternate Nostril Breathing (Nadi Shodhana)',
    description: 'Balance your energy with this ancient yogic technique',
    type: 'breathing',
    duration: 10,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=8VwufJrUhic',
    views: '5M+',
    popularity: 7,
    instructor: 'Yoga With Adriene',
    tags: ['nadi shodhana', 'balance', 'energy']
  },
  {
    id: 'br-8',
    title: 'Breath of Fire (Kapalabhati)',
    description: 'Energizing breathing technique to wake up your body',
    type: 'breathing',
    duration: 8,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=jbtLH-3DfLc',
    views: '4M+',
    popularity: 8,
    instructor: 'Yoga With Adriene',
    tags: ['kapalabhati', 'energy', 'morning']
  },
  {
    id: 'br-9',
    title: 'Coherent Breathing - 5 Breaths Per Minute',
    description: 'Optimize your heart rate variability with coherent breathing',
    type: 'breathing',
    duration: 10,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=zMEFBM0pEQw',
    views: '3M+',
    popularity: 9,
    instructor: 'Take A Deep Breath',
    tags: ['coherent breathing', 'hrv', 'heart health']
  },
  {
    id: 'br-10',
    title: 'Diaphragmatic Breathing Exercise',
    description: 'Learn proper belly breathing for deep relaxation',
    type: 'breathing',
    duration: 12,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=UB3tSaiEbNY',
    views: '6M+',
    popularity: 10,
    instructor: 'Therapy in a Nutshell',
    tags: ['diaphragmatic', 'belly breathing', 'relaxation']
  },
  {
    id: 'br-11',
    title: 'Simple Breathing Techniques',
    description: 'Square breathing and pursed lip breathing for stress',
    type: 'breathing',
    duration: 10,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=aXItOY0sLRY',
    views: '7M+',
    popularity: 11,
    instructor: 'Ask Doctor Jo',
    tags: ['physio', 'techniques', 'simple']
  },
  {
    id: 'br-12',
    title: 'Ocean Breath (Ujjayi Pranayama)',
    description: 'The victorious breath for yoga and meditation',
    type: 'breathing',
    duration: 8,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=IQrsJ-yZWV8',
    views: '2M+',
    popularity: 12,
    instructor: 'Yoga With Adriene',
    tags: ['ujjayi', 'ocean breath', 'yoga']
  },
  {
    id: 'br-13',
    title: 'Breathing for Anxiety Tools',
    description: 'Part of 20 grounding techniques for anxiety',
    type: 'breathing',
    duration: 7,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=30VMIEmA114',
    views: '9M+',
    popularity: 13,
    instructor: 'Therapy in a Nutshell',
    tags: ['anxiety', 'panic', 'emergency']
  },
  {
    id: 'br-14',
    title: 'Morning Breathing Routine',
    description: 'Energize your day with this morning breath practice',
    type: 'breathing',
    duration: 10,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=YtAD8pDUEzo',
    views: '4M+',
    popularity: 14,
    instructor: 'Breathe and Flow',
    tags: ['morning', 'energy', 'routine']
  },
  {
    id: 'br-15',
    title: 'Evening Wind-Down Breathing',
    description: 'Relax your nervous system before bed',
    type: 'breathing',
    duration: 15,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=JUFRvnF__ho',
    views: '3M+',
    popularity: 15,
    instructor: 'Michael Sealey',
    tags: ['evening', 'sleep prep', 'wind down']
  },
  {
    id: 'br-16',
    title: 'Buteyko Breathing Method',
    description: 'Improve your breathing efficiency with Buteyko',
    type: 'breathing',
    duration: 20,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=aIx7Ph_YOPA',
    views: '2M+',
    popularity: 16,
    instructor: 'Patrick McKeown',
    tags: ['buteyko', 'efficiency', 'nasal breathing']
  },
  {
    id: 'br-17',
    title: 'Box Breathing for Stress Relief',
    description: 'How to use box breathing to lower stress',
    type: 'breathing',
    duration: 12,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=tEmt1Znux58',
    views: '5M+',
    popularity: 17,
    instructor: 'Your Wellness Nerd',
    tags: ['focus', 'concentration', 'work']
  },
  {
    id: 'br-18',
    title: 'Sitali Cooling Breath',
    description: 'Cool down your body and mind with this technique',
    type: 'breathing',
    duration: 6,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=gLmMZxkZWFA',
    views: '1M+',
    popularity: 18,
    instructor: 'Yoga With Adriene',
    tags: ['cooling', 'summer', 'calm']
  },
  {
    id: 'br-19',
    title: 'Three-Part Breath (Dirga Pranayama)',
    description: 'Complete yogic breath for full lung capacity',
    type: 'breathing',
    duration: 10,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=0HrqjS0dSxA',
    views: '2M+',
    popularity: 19,
    instructor: 'Yoga With Adriene',
    tags: ['three-part', 'full breath', 'yoga']
  },
  {
    id: 'br-20',
    title: 'Holotropic Breathwork Introduction',
    description: 'Powerful breathwork for altered states of consciousness',
    type: 'breathing',
    duration: 25,
    level: 'advanced',
    videoUrl: 'https://www.youtube.com/watch?v=yHH3_sH4vxs',
    views: '3M+',
    popularity: 20,
    instructor: 'Stanislav Grof',
    tags: ['holotropic', 'altered states', 'deep work']
  },
  {
    id: 'br-21',
    title: 'Breathing for Pain Management',
    description: 'Use breath to reduce physical pain naturally',
    type: 'breathing',
    duration: 15,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=aNXKjGFUlMs',
    views: '2M+',
    popularity: 21,
    instructor: 'Therapy in a Nutshell',
    tags: ['pain', 'chronic pain', 'relief']
  },
  {
    id: 'br-22',
    title: '2-Minute Breathing Reset',
    description: 'Ultra-quick breathing exercise for busy moments',
    type: 'breathing',
    duration: 2,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=0Xb-oLS-cyY',
    views: '4M+',
    popularity: 22,
    instructor: 'Headspace',
    tags: ['quick', 'reset', 'office']
  },
  {
    id: 'br-23',
    title: 'Breathing for Athletes',
    description: 'Performance breathing for sports and fitness',
    type: 'breathing',
    duration: 15,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=2wP_JpFj9lw',
    views: '1M+',
    popularity: 23,
    instructor: 'Brian Mackenzie',
    tags: ['athletes', 'performance', 'fitness']
  },
  {
    id: 'br-24',
    title: 'Breathing Before Public Speaking',
    description: 'Calm your nerves before presentations',
    type: 'breathing',
    duration: 5,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=v8B80SDDKRE',
    views: '2M+',
    popularity: 24,
    instructor: 'TEDx Talks',
    tags: ['public speaking', 'nerves', 'performance']
  },
  {
    id: 'br-25',
    title: 'Advanced Pranayama Sequence',
    description: 'Complete pranayama practice for experienced yogis',
    type: 'breathing',
    duration: 30,
    level: 'advanced',
    videoUrl: 'https://www.youtube.com/watch?v=Qp4WkbhCwWc',
    views: '1M+',
    popularity: 25,
    instructor: 'Yoga With Tim',
    tags: ['advanced', 'sequence', 'complete']
  }
]

// ============================================
// MINDFULNESS MEDITATIONS (25 sessions)
// ============================================
export const mindfulnessMeditations: MeditationData[] = [
  {
    id: 'mf-1',
    title: 'Body Scan Meditation',
    description: 'Full body awareness and relaxation meditation',
    type: 'mindfulness',
    duration: 45,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=u4gZgnCy5ew',
    views: '30M+',
    popularity: 1,
    instructor: 'Jon Kabat-Zinn',
    tags: ['body scan', 'awareness', 'relaxation']
  },
  {
    id: 'mf-2',
    title: 'Mindfulness Meditation - Guided 10 Minutes',
    description: 'Simple introduction to mindfulness practice',
    type: 'mindfulness',
    duration: 10,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=6p_yaNFSYao',
    views: '25M+',
    popularity: 2,
    instructor: 'The Honest Guys',
    tags: ['introduction', 'simple', 'daily']
  },
  {
    id: 'mf-3',
    title: 'Present Moment Awareness',
    description: 'Cultivate awareness of the here and now',
    type: 'mindfulness',
    duration: 15,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=shCeh3_WPzY',
    views: '18M+',
    popularity: 3,
    instructor: 'Eckhart Tolle',
    tags: ['present moment', 'now', 'awareness']
  },
  {
    id: 'mf-4',
    title: 'Focus & Clarity Meditation',
    description: 'Improve concentration and mental clarity',
    type: 'mindfulness',
    duration: 25,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=ssss7V1_eyA',
    views: '12M+',
    popularity: 4,
    instructor: 'Calm',
    tags: ['focus', 'clarity', 'concentration']
  },
  {
    id: 'mf-5',
    title: 'RAIN Meditation for Difficult Emotions',
    description: 'Recognize, Allow, Investigate, Nurture your emotions',
    type: 'mindfulness',
    duration: 20,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=W8e_tAEM80k',
    views: '5M+',
    popularity: 5,
    instructor: 'Tara Brach',
    tags: ['RAIN', 'emotions', 'self-compassion']
  },
  {
    id: 'mf-6',
    title: 'Walking Meditation Guide',
    description: 'Practice mindfulness while walking',
    type: 'mindfulness',
    duration: 15,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=QdO1vZJgUu0',
    views: '3M+',
    popularity: 6,
    instructor: 'Thich Nhat Hanh',
    tags: ['walking', 'movement', 'outdoors']
  },
  {
    id: 'mf-7',
    title: 'Mindful Eating Meditation',
    description: 'Bring awareness to your eating experience',
    type: 'mindfulness',
    duration: 10,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=6tw93IgfL0U',
    views: '2M+',
    popularity: 7,
    instructor: 'Jon Kabat-Zinn',
    tags: ['eating', 'food', 'awareness']
  },
  {
    id: 'mf-8',
    title: 'Grounding Techniques Compilation',
    description: '20 ways to ground yourself including 5 senses',
    type: 'mindfulness',
    duration: 10,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=30VMIEmA114',
    views: '8M+',
    popularity: 8,
    instructor: 'Therapy in a Nutshell',
    tags: ['grounding', 'senses', 'anxiety']
  },
  {
    id: 'mf-9',
    title: 'Noting Practice Meditation',
    description: 'Label your thoughts to create distance',
    type: 'mindfulness',
    duration: 15,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=FjI9v-VYwZY',
    views: '2M+',
    popularity: 9,
    instructor: 'Joseph Goldstein',
    tags: ['noting', 'labeling', 'thoughts']
  },
  {
    id: 'mf-10',
    title: 'Open Awareness Meditation',
    description: 'Expand your awareness to everything around you',
    type: 'mindfulness',
    duration: 20,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=-wIt_WsJGfw',
    views: '3M+',
    popularity: 10,
    instructor: 'Sam Harris',
    tags: ['open awareness', 'spacious', 'advanced']
  },
  {
    id: 'mf-11',
    title: 'Mindfulness for Beginners - Day 1',
    description: 'Start your mindfulness journey here',
    type: 'mindfulness',
    duration: 10,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=w6T02g5hnT4',
    views: '10M+',
    popularity: 11,
    instructor: 'Goodful',
    tags: ['beginner', 'day 1', 'start']
  },
  {
    id: 'mf-12',
    title: 'Acceptance Meditation',
    description: 'Learn to accept what is without resistance',
    type: 'mindfulness',
    duration: 18,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=FGpzpMD0KDc',
    views: '4M+',
    popularity: 12,
    instructor: 'Tara Brach',
    tags: ['acceptance', 'letting go', 'peace']
  },
  {
    id: 'mf-13',
    title: 'Mindfulness of Sound',
    description: 'Use sounds as anchors for awareness',
    type: 'mindfulness',
    duration: 12,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=QHkXvPq2pQE',
    views: '2M+',
    popularity: 13,
    instructor: 'The Honest Guys',
    tags: ['sound', 'listening', 'anchor']
  },
  {
    id: 'mf-14',
    title: 'Self-Compassion Meditation',
    description: 'Cultivate kindness towards yourself',
    type: 'mindfulness',
    duration: 15,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=wzHjTICAR6w',
    views: '6M+',
    popularity: 14,
    instructor: 'Kristin Neff',
    tags: ['self-compassion', 'kindness', 'self-love']
  },
  {
    id: 'mf-15',
    title: 'Choiceless Awareness Meditation',
    description: 'Advanced practice of non-directed attention',
    type: 'mindfulness',
    duration: 25,
    level: 'advanced',
    videoUrl: 'https://www.youtube.com/watch?v=kE_kyqijCBY',
    views: '1M+',
    popularity: 15,
    instructor: 'Jiddu Krishnamurti',
    tags: ['choiceless', 'advanced', 'pure awareness']
  },
  {
    id: 'mf-16',
    title: 'Mindful Movement Meditation',
    description: 'Combine gentle movement with awareness',
    type: 'mindfulness',
    duration: 20,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=COp7BR_Dvps',
    views: '4M+',
    popularity: 16,
    instructor: 'Yoga With Adriene',
    tags: ['movement', 'gentle', 'body']
  },
  {
    id: 'mf-17',
    title: 'Observing Thoughts Meditation',
    description: 'Watch your thoughts like clouds passing',
    type: 'mindfulness',
    duration: 15,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=ez3GgRqhNvA',
    views: '3M+',
    popularity: 17,
    instructor: 'Michael Sealey',
    tags: ['thoughts', 'observing', 'detachment']
  },
  {
    id: 'mf-18',
    title: 'Morning Mindfulness Routine',
    description: 'Start your day with presence and intention',
    type: 'mindfulness',
    duration: 10,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=xRxT9cOKiM8',
    views: '7M+',
    popularity: 18,
    instructor: 'Great Meditation',
    tags: ['morning', 'routine', 'intention']
  },
  {
    id: 'mf-19',
    title: 'Mindfulness at Your Desk',
    description: '8-minute meditation you can do at your desk',
    type: 'mindfulness',
    duration: 8,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=F0Y04Rk84x8',
    views: '3M+',
    popularity: 19,
    instructor: 'Headspace',
    tags: ['work', 'office', 'quick']
  },
  {
    id: 'mf-20',
    title: 'Advanced Vipassana Meditation',
    description: 'Deep insight meditation practice',
    type: 'mindfulness',
    duration: 45,
    level: 'advanced',
    videoUrl: 'https://www.youtube.com/watch?v=OBoW8pT2SJg',
    views: '11M+',
    popularity: 20,
    instructor: 'S.N. Goenka',
    tags: ['vipassana', 'insight', 'deep']
  },
  {
    id: 'mf-21',
    title: 'Equanimity Meditation',
    description: 'Develop balanced awareness in all situations',
    type: 'mindfulness',
    duration: 20,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=Jy8e4dqO0Kk',
    views: '2M+',
    popularity: 21,
    instructor: 'Sharon Salzberg',
    tags: ['equanimity', 'balance', 'stability']
  },
  {
    id: 'mf-22',
    title: 'Mindfulness for Overthinking',
    description: 'Break free from rumination and worry',
    type: 'mindfulness',
    duration: 15,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=1vx8iUvfyCY',
    views: '8M+',
    popularity: 22,
    instructor: 'Great Meditation',
    tags: ['overthinking', 'worry', 'rumination']
  },
  {
    id: 'mf-23',
    title: '5-Minute Mindfulness Reset',
    description: 'Quick mindfulness break for your day',
    type: 'mindfulness',
    duration: 5,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=inpok4MKVLM',
    views: '4M+',
    popularity: 23,
    instructor: 'Goodful',
    tags: ['gratitude', 'appreciation', 'positive']
  },
  {
    id: 'mf-24',
    title: 'Non-Judgmental Awareness',
    description: 'Practice observing without labeling good or bad',
    type: 'mindfulness',
    duration: 18,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=p7PZvidqeHw',
    views: '2M+',
    popularity: 24,
    instructor: 'Tara Brach',
    tags: ['non-judgmental', 'acceptance', 'neutral']
  },
  {
    id: 'mf-25',
    title: 'Zen Meditation (Zazen) Introduction',
    description: 'Traditional Zen sitting meditation',
    type: 'mindfulness',
    duration: 20,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=FKhonr5Z2UM',
    views: '3M+',
    popularity: 25,
    instructor: 'Zen Master',
    tags: ['zen', 'zazen', 'traditional']
  }
]

// ============================================
// VISUALIZATION MEDITATIONS (25 sessions)
// ============================================
export const visualizationMeditations: MeditationData[] = [
  {
    id: 'vs-1',
    title: 'Silva Centering Exercise',
    description: 'Vishen Lakhiani guides you through the Silva Centering exercise',
    type: 'visualization',
    duration: 20,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=9HyOZ6xL_oM',
    views: '20M+',
    popularity: 1,
    instructor: 'Vishen Lakhiani',
    tags: ['silva method', 'manifestation', 'mind control']
  },
  {
    id: 'vs-2',
    title: 'Silva Method Problem Solving',
    description: 'Use the Silva technique to find solutions',
    type: 'visualization',
    duration: 20,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=3T3QLmgpOWU',
    views: '5M+',
    popularity: 2,
    instructor: 'Silva Method',
    tags: ['silva method', 'problem solving', 'alpha']
  },
  {
    id: 'vs-3',
    title: 'Guided Visualization for Success',
    description: 'Manifest your goals through visualization',
    type: 'visualization',
    duration: 15,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=YMF5h6HpxKk',
    views: '15M+',
    popularity: 3,
    instructor: 'Bob Proctor',
    tags: ['success', 'goals', 'manifestation']
  },
  {
    id: 'vs-4',
    title: 'Loving Kindness Meditation (Metta)',
    description: 'Cultivate compassion and positive emotions',
    type: 'visualization',
    duration: 15,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=sz7cpV7ERsM',
    views: '22M+',
    popularity: 4,
    instructor: 'Sharon Salzberg',
    tags: ['metta', 'loving kindness', 'compassion']
  },
  {
    id: 'vs-5',
    title: 'Future Self Visualization',
    description: 'Connect with your best possible future self',
    type: 'visualization',
    duration: 20,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=v6-c8NOneUM',
    views: '8M+',
    popularity: 5,
    instructor: 'Dr. Joe Dispenza',
    tags: ['future self', 'potential', 'transformation']
  },
  {
    id: 'vs-6',
    title: 'Healing Light Meditation',
    description: 'Visualize healing energy throughout your body',
    type: 'visualization',
    duration: 25,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=oA_rY4N8XJA',
    views: '10M+',
    popularity: 6,
    instructor: 'Michael Sealey',
    tags: ['healing', 'light', 'health']
  },
  {
    id: 'vs-7',
    title: 'Safe Place Visualization',
    description: 'Create your inner sanctuary for peace',
    type: 'visualization',
    duration: 15,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=LomAPbJ6Huk',
    views: '6M+',
    popularity: 7,
    instructor: 'Yogini Melbourne',
    tags: ['safe place', 'sanctuary', 'peace']
  },
  {
    id: 'vs-8',
    title: 'Abundance Visualization',
    description: 'Attract prosperity and abundance',
    type: 'visualization',
    duration: 20,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=cwPoUGzM-iY',
    views: '12M+',
    popularity: 8,
    instructor: 'Abraham Hicks',
    tags: ['abundance', 'prosperity', 'law of attraction']
  },
  {
    id: 'vs-9',
    title: 'Inner Child Healing Visualization',
    description: 'Reconnect with and heal your inner child',
    type: 'visualization',
    duration: 25,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=7_bAQi0Yr68',
    views: '5M+',
    popularity: 9,
    instructor: 'Michael Sealey',
    tags: ['inner child', 'healing', 'emotional']
  },
  {
    id: 'vs-10',
    title: 'Beach Visualization for Relaxation',
    description: 'Imagine yourself on a peaceful beach',
    type: 'visualization',
    duration: 15,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=_ZeEPo8w-n8',
    views: '9M+',
    popularity: 10,
    instructor: 'Dr. Jen Andrews',
    tags: ['beach', 'relaxation', 'nature']
  },
  {
    id: 'vs-11',
    title: 'Mountain Meditation',
    description: 'Embody the stability and strength of a mountain',
    type: 'visualization',
    duration: 18,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=yW_-d84Igxw',
    views: '4M+',
    popularity: 11,
    instructor: 'Jon Kabat-Zinn',
    tags: ['mountain', 'stability', 'strength']
  },
  {
    id: 'vs-12',
    title: 'Chakra Visualization Journey',
    description: 'Visualize and balance your seven chakras',
    type: 'visualization',
    duration: 30,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=DdL9-NhXL6k',
    views: '7M+',
    popularity: 12,
    instructor: 'Jason Stephenson',
    tags: ['chakra', 'energy', 'balance']
  },
  {
    id: 'vs-13',
    title: 'Goal Achievement Visualization',
    description: 'Visualize achieving your most important goal',
    type: 'visualization',
    duration: 15,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=e-xl32w5Rz0',
    views: '5M+',
    popularity: 13,
    instructor: 'Bob Baker',
    tags: ['goals', 'achievement', 'success']
  },
  {
    id: 'vs-14',
    title: 'Transcendental Meditation Guide',
    description: 'Introduction to TM-style meditation',
    type: 'visualization',
    duration: 20,
    level: 'advanced',
    videoUrl: 'https://www.youtube.com/watch?v=fO3AnD2QbIg',
    views: '8M+',
    popularity: 14,
    instructor: 'Bob Roth',
    tags: ['transcendental', 'TM', 'mantra']
  },
  {
    id: 'vs-15',
    title: 'Kundalini Awakening Meditation',
    description: 'Advanced energy work for spiritual growth',
    type: 'visualization',
    duration: 30,
    level: 'advanced',
    videoUrl: 'https://www.youtube.com/watch?v=wymi3AxcqnU',
    views: '6M+',
    popularity: 15,
    instructor: 'Sadhguru',
    tags: ['kundalini', 'energy', 'awakening']
  },
  {
    id: 'vs-16',
    title: 'Forest Sounds Ambience',
    description: 'Relaxing woodland ambience without music',
    type: 'visualization',
    duration: 20,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=xNN7iTA57jM',
    views: '8M+',
    popularity: 16,
    instructor: 'The Guild of Ambience',
    tags: ['forest', 'nature', 'walk']
  },
  {
    id: 'vs-17',
    title: 'Creative Visualization for Artists',
    description: 'Enhance creativity through visualization',
    type: 'visualization',
    duration: 18,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=8q332pIPcCc',
    views: '2M+',
    popularity: 17,
    instructor: 'Shakti Gawain',
    tags: ['creativity', 'artists', 'inspiration']
  },
  {
    id: 'vs-18',
    title: 'Confidence Visualization',
    description: 'Build unshakeable confidence through imagery',
    type: 'visualization',
    duration: 15,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=7MijJQIWOeU',
    views: '6M+',
    popularity: 18,
    instructor: 'Michael Sealey',
    tags: ['confidence', 'self-esteem', 'power']
  },
  {
    id: 'vs-19',
    title: 'Releasing Negative Energy Visualization',
    description: 'Let go of negative emotions and energy',
    type: 'visualization',
    duration: 20,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=86m4RC_ADEY',
    views: '5M+',
    popularity: 19,
    instructor: 'Jason Stephenson',
    tags: ['release', 'negative', 'letting go']
  },
  {
    id: 'vs-20',
    title: 'Perfect Day Visualization',
    description: 'Visualize your ideal day from start to finish',
    type: 'visualization',
    duration: 12,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=DDDXeZ0IHVo',
    views: '3M+',
    popularity: 20,
    instructor: 'My Peace of Mindfulness',
    tags: ['perfect day', 'morning', 'intention']
  },
  {
    id: 'vs-21',
    title: 'Body Healing Visualization',
    description: 'Direct healing energy to specific body parts',
    type: 'visualization',
    duration: 25,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=MWT6DYq4uas',
    views: '4M+',
    popularity: 21,
    instructor: 'The Mindful Movement',
    tags: ['body healing', 'health', 'recovery']
  },
  {
    id: 'vs-22',
    title: 'Relationship Visualization',
    description: 'Manifest loving relationships',
    type: 'visualization',
    duration: 18,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=j_Q8yCGEZdM',
    views: '3M+',
    popularity: 22,
    instructor: 'Pura Rasa',
    tags: ['relationships', 'love', 'connection']
  },
  {
    id: 'vs-23',
    title: 'Star Journey Visualization',
    description: 'Journey through the cosmos',
    type: 'visualization',
    duration: 20,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=GXxj9uvJi-o',
    views: '5M+',
    popularity: 23,
    instructor: 'The Honest Guys',
    tags: ['space', 'cosmos', 'journey']
  },
  {
    id: 'vs-24',
    title: 'Weight Loss Visualization',
    description: 'Visualize your ideal healthy body',
    type: 'visualization',
    duration: 15,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=E5dE0Itdqk8',
    views: '4M+',
    popularity: 24,
    instructor: 'Michael Sealey',
    tags: ['weight loss', 'health', 'body']
  },
  {
    id: 'vs-25',
    title: 'Third Eye Activation Meditation',
    description: 'Open and activate your third eye chakra',
    type: 'visualization',
    duration: 30,
    level: 'advanced',
    videoUrl: 'https://www.youtube.com/watch?v=Iq5HQU_uMUI',
    views: '7M+',
    popularity: 25,
    instructor: 'My Peace of Mindfulness',
    tags: ['third eye', 'intuition', 'awakening']
  }
]

// ============================================
// STRESS RELIEF MEDITATIONS (20 sessions)
// ============================================
export const stressReliefMeditations: MeditationData[] = [
  {
    id: 'sr-1',
    title: '10-Minute Stress Relief Meditation',
    description: 'Release tension and calm your nervous system',
    type: 'stress_relief',
    duration: 10,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=z6X5oEIg6Ak',
    views: '40M+',
    popularity: 1,
    instructor: 'Goodful',
    tags: ['stress', 'tension', 'quick']
  },
  {
    id: 'sr-2',
    title: 'Anxiety & Fear Meditation',
    description: 'Guided meditation for anxiety and fear',
    type: 'stress_relief',
    duration: 20,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=O-6f5wQXSu8',
    views: '25M+',
    popularity: 2,
    instructor: 'Boho Beautiful Yoga',
    tags: ['anxiety', 'peace', 'calm']
  },
  {
    id: 'sr-3',
    title: '5-Minute Stress Relief Breathing',
    description: 'Quick box breathing technique',
    type: 'stress_relief',
    duration: 5,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=tEmt1Znux58',
    views: '16M+',
    popularity: 3,
    instructor: 'Your Wellness Nerd',
    tags: ['quick', 'overthinking', 'calm']
  },
  {
    id: 'sr-4',
    title: 'Progressive Muscle Relaxation',
    description: 'Systematically release tension from your body',
    type: 'stress_relief',
    duration: 15,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=SNqYGEz-Qd4',
    views: '12M+',
    popularity: 4,
    instructor: 'Therapy in a Nutshell',
    tags: ['PMR', 'muscle relaxation', 'body']
  },
  {
    id: 'sr-5',
    title: 'Emergency Anxiety Tools',
    description: 'STOP method and grounding for panic',
    type: 'stress_relief',
    duration: 8,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=30VMIEmA114',
    views: '10M+',
    popularity: 5,
    instructor: 'Therapy in a Nutshell',
    tags: ['emergency', 'panic', 'immediate']
  },
  {
    id: 'sr-6',
    title: 'Stress Relief Before Bed',
    description: 'Release the day\'s stress before sleep',
    type: 'stress_relief',
    duration: 15,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=lu_cLaBTXio',
    views: '8M+',
    popularity: 6,
    instructor: 'The Honest Guys',
    tags: ['evening', 'sleep prep', 'release']
  },
  {
    id: 'sr-7',
    title: '10-Minute Stress Meditation',
    description: 'Headspace mini-meditation for stress',
    type: 'stress_relief',
    duration: 10,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=lS0kcSNlULw',
    views: '5M+',
    popularity: 7,
    instructor: 'Headspace',
    tags: ['work', 'office', 'decompress']
  },
  {
    id: 'sr-8',
    title: 'Letting Go of Worry',
    description: 'Release worries that you cannot control',
    type: 'stress_relief',
    duration: 18,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=2K4T1CQx1vY',
    views: '6M+',
    popularity: 8,
    instructor: 'Michael Sealey',
    tags: ['worry', 'letting go', 'control']
  },
  {
    id: 'sr-9',
    title: 'Nervous System Reset',
    description: 'Activate your parasympathetic nervous system',
    type: 'stress_relief',
    duration: 12,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=PmQn9YrJ8YI',
    views: '4M+',
    popularity: 9,
    instructor: 'Sukie Baxter',
    tags: ['nervous system', 'vagus nerve', 'reset']
  },
  {
    id: 'sr-10',
    title: 'Stress Relief Body Scan',
    description: 'Find and release tension throughout your body',
    type: 'stress_relief',
    duration: 20,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=zsCVqFr6j1g',
    views: '7M+',
    popularity: 10,
    instructor: 'Jason Stephenson',
    tags: ['body scan', 'tension', 'release']
  },
  {
    id: 'sr-11',
    title: 'Quick Desk Meditation',
    description: 'Stress relief without leaving your desk',
    type: 'stress_relief',
    duration: 5,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=4pKly2JojMw',
    views: '3M+',
    popularity: 11,
    instructor: 'Headspace',
    tags: ['desk', 'office', 'quick']
  },
  {
    id: 'sr-12',
    title: 'Stress and Anger Release',
    description: 'Let go of frustration and anger',
    type: 'stress_relief',
    duration: 15,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=pYn55qEnXok',
    views: '5M+',
    popularity: 12,
    instructor: 'Michael Sealey',
    tags: ['anger', 'frustration', 'release']
  },
  {
    id: 'sr-13',
    title: 'Calming the Mind Storm',
    description: 'Find peace when thoughts are overwhelming',
    type: 'stress_relief',
    duration: 12,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=FbJl1SGkNcE',
    views: '4M+',
    popularity: 13,
    instructor: 'Great Meditation',
    tags: ['overwhelm', 'thoughts', 'calm']
  },
  {
    id: 'sr-14',
    title: 'Stress Relief with Nature Sounds',
    description: 'Relax with soothing nature soundscape',
    type: 'stress_relief',
    duration: 20,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=lFcSrYw-ARY',
    views: '15M+',
    popularity: 14,
    instructor: 'Relaxing White Noise',
    tags: ['nature', 'sounds', 'ambient']
  },
  {
    id: 'sr-15',
    title: 'Social Anxiety Relief',
    description: 'Calm social anxiety before events',
    type: 'stress_relief',
    duration: 12,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=3p6N8RVRxMg',
    views: '3M+',
    popularity: 15,
    instructor: 'Michael Sealey',
    tags: ['social anxiety', 'events', 'confidence']
  },
  {
    id: 'sr-16',
    title: 'Stress-Free Morning',
    description: 'Start your day without stress',
    type: 'stress_relief',
    duration: 10,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=ENYYb5vIMkU',
    views: '6M+',
    popularity: 16,
    instructor: 'Great Meditation',
    tags: ['morning', 'start', 'peace']
  },
  {
    id: 'sr-17',
    title: 'Deep Relaxation Journey',
    description: 'Go into a state of deep relaxation',
    type: 'stress_relief',
    duration: 25,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=wGN2jJiYEp0',
    views: '8M+',
    popularity: 17,
    instructor: 'Michael Sealey',
    tags: ['deep relaxation', 'journey', 'peaceful']
  },
  {
    id: 'sr-18',
    title: 'Exam Stress Relief',
    description: 'Calm pre-exam anxiety',
    type: 'stress_relief',
    duration: 10,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=1ZYbU82GVz4',
    views: '4M+',
    popularity: 18,
    instructor: 'Great Meditation',
    tags: ['exam', 'test', 'students']
  },
  {
    id: 'sr-19',
    title: 'Release Physical Stress',
    description: 'Let go of stress stored in your body',
    type: 'stress_relief',
    duration: 15,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=uxayUBd6T7M',
    views: '5M+',
    popularity: 19,
    instructor: 'Jason Stephenson',
    tags: ['physical', 'body', 'tension']
  },
  {
    id: 'sr-20',
    title: 'Weekend Stress Recovery',
    description: 'Recover from a stressful week',
    type: 'stress_relief',
    duration: 30,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=A8jl8xEFBWo',
    views: '3M+',
    popularity: 20,
    instructor: 'Michael Sealey',
    tags: ['weekend', 'recovery', 'deep']
  }
]

// ============================================
// SLEEP MEDITATIONS (20 sessions)
// ============================================
export const sleepMeditations: MeditationData[] = [
  {
    id: 'sl-1',
    title: 'Deep Sleep Meditation',
    description: 'Fall asleep fast with this guided meditation',
    type: 'sleep',
    duration: 60,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=hJbRpHZr_d0',
    views: '65M+',
    popularity: 1,
    instructor: 'Jason Stephenson',
    tags: ['deep sleep', 'fall asleep', 'guided']
  },
  {
    id: 'sl-2',
    title: 'Sleep Hypnosis for Deep Rest',
    description: 'Journey into deep relaxation and restful sleep',
    type: 'sleep',
    duration: 60,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=ecV6qxyynGI',
    views: '28M+',
    popularity: 2,
    instructor: 'Michael Sealey',
    tags: ['hypnosis', 'deep rest', 'long']
  },
  {
    id: 'sl-3',
    title: 'Sleep in 20 Minutes',
    description: 'Quick path to peaceful sleep',
    type: 'sleep',
    duration: 20,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=lu_cLaBTXio',
    views: '38M+',
    popularity: 3,
    instructor: 'The Honest Guys',
    tags: ['20 minutes', 'quick', 'peaceful']
  },
  {
    id: 'sl-4',
    title: 'Sleep Stories: The Rainforest',
    description: 'Drift off to a peaceful rainforest journey',
    type: 'sleep',
    duration: 45,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=R5uFlsfP9p8',
    views: '20M+',
    popularity: 4,
    instructor: 'Calm',
    tags: ['sleep story', 'rainforest', 'nature']
  },
  {
    id: 'sl-5',
    title: 'Yoga Nidra for Sleep',
    description: 'Yogic sleep meditation for deep rest',
    type: 'sleep',
    duration: 40,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=7H5n6H2Kz_g',
    views: '15M+',
    popularity: 5,
    instructor: 'Ally Boothroyd',
    tags: ['yoga nidra', 'yogic sleep', 'deep']
  },
  {
    id: 'sl-6',
    title: 'Binaural Beats for Sleep (Delta Waves)',
    description: 'Delta wave frequencies for deep sleep',
    type: 'sleep',
    duration: 60,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=tNkZsRW7h2c',
    views: '35M+',
    popularity: 6,
    instructor: 'Brainwave Hub',
    tags: ['binaural', 'delta', 'frequencies']
  },
  {
    id: 'sl-7',
    title: 'Body Relaxation for Sleep',
    description: 'Progressive relaxation to drift into sleep',
    type: 'sleep',
    duration: 25,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=J9f2g7Z_b60',
    views: '12M+',
    popularity: 7,
    instructor: 'The Honest Guys',
    tags: ['body relaxation', 'progressive', 'drift']
  },
  {
    id: 'sl-8',
    title: 'Insomnia Relief Meditation',
    description: 'Designed specifically for those with insomnia',
    type: 'sleep',
    duration: 35,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=rW1i29Xj9kI',
    views: '18M+',
    popularity: 8,
    instructor: 'Michael Sealey',
    tags: ['insomnia', 'can\'t sleep', 'relief']
  },
  {
    id: 'sl-9',
    title: 'Deep Sleep Journey',
    description: 'Guided deep sleep meditation',
    type: 'sleep',
    duration: 60,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=hJbRpHZr_d0',
    views: '10M+',
    popularity: 9,
    instructor: 'Jason Stephenson',
    tags: ['sleep story', 'train', 'journey']
  },
  {
    id: 'sl-10',
    title: 'Ocean Waves Sleep Meditation',
    description: 'Fall asleep to gentle ocean sounds',
    type: 'sleep',
    duration: 60,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=f77SKdyn-Kk',
    views: '25M+',
    popularity: 10,
    instructor: 'Relaxing White Noise',
    tags: ['ocean', 'waves', 'nature sounds']
  },
  {
    id: 'sl-11',
    title: 'Rain Sounds Sleep',
    description: 'Peaceful rain sounds for deep sleep',
    type: 'sleep',
    duration: 60,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=mPZkdNFkNps',
    views: '45M+',
    popularity: 11,
    instructor: 'Relaxing White Noise',
    tags: ['rain', 'sounds', 'ambient']
  },
  {
    id: 'sl-12',
    title: 'Relaxing Breathing for Sleep',
    description: 'Simple breathing techniques to relax',
    type: 'sleep',
    duration: 10,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=aXItOY0sLRY',
    views: '8M+',
    popularity: 12,
    instructor: 'Ask Doctor Jo',
    tags: ['quick', '10 minutes', 'fast']
  },
  {
    id: 'sl-13',
    title: 'Sleep Visualization Journey',
    description: 'Journey through peaceful landscapes as you sleep',
    type: 'sleep',
    duration: 40,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=fWXpQAv9hR8',
    views: '9M+',
    popularity: 13,
    instructor: 'The Honest Guys',
    tags: ['visualization', 'journey', 'landscapes']
  },
  {
    id: 'sl-14',
    title: 'Calm Anxiety Before Bed',
    description: 'Release anxiety to find sleep',
    type: 'sleep',
    duration: 25,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=O-6f5wQXSu8',
    views: '15M+',
    popularity: 14,
    instructor: 'Boho Beautiful Yoga',
    tags: ['anxiety', 'release', 'bed']
  },
  {
    id: 'sl-15',
    title: 'Counting Down to Sleep',
    description: 'Countdown technique for falling asleep',
    type: 'sleep',
    duration: 20,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=5VuSrt_TMFo',
    views: '6M+',
    popularity: 15,
    instructor: 'Great Meditation',
    tags: ['counting', 'technique', 'simple']
  },
  {
    id: 'sl-16',
    title: 'Sleep Hypnosis: Floating on Clouds',
    description: 'Float on clouds into peaceful sleep',
    type: 'sleep',
    duration: 45,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=JFf4vV5GKZ0',
    views: '11M+',
    popularity: 16,
    instructor: 'Sleep Easy Relax',
    tags: ['hypnosis', 'clouds', 'floating']
  },
  {
    id: 'sl-17',
    title: 'Sleep Stories: The Cottage',
    description: 'A cozy cottage sleep story',
    type: 'sleep',
    duration: 35,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=kDCTGqjqR6A',
    views: '7M+',
    popularity: 17,
    instructor: 'The Honest Guys',
    tags: ['sleep story', 'cottage', 'cozy']
  },
  {
    id: 'sl-18',
    title: 'Deep Sleep Relaxation Music',
    description: 'Calming music designed for deep sleep',
    type: 'sleep',
    duration: 60,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=4FHoGgpMlI8',
    views: '30M+',
    popularity: 18,
    instructor: 'Yellow Brick Cinema',
    tags: ['music', 'relaxation', 'no talking']
  },
  {
    id: 'sl-19',
    title: 'Body Scan for Sleep',
    description: 'Relax your body to fall asleep',
    type: 'sleep',
    duration: 45,
    level: 'beginner',
    videoUrl: 'https://www.youtube.com/watch?v=u4gZgnCy5ew',
    views: '5M+',
    popularity: 19,
    instructor: 'Jon Kabat-Zinn',
    tags: ['gratitude', 'bedtime', 'positive']
  },
  {
    id: 'sl-20',
    title: 'Weekend Stress Recovery',
    description: 'Recover from a stressful week',
    type: 'sleep',
    duration: 30,
    level: 'intermediate',
    videoUrl: 'https://www.youtube.com/watch?v=A8jl8xEFBWo',
    views: '8M+',
    popularity: 20,
    instructor: 'Michael Sealey',
    tags: ['stress', 'reset', 'recover']
  }
]

// ============================================
// COMBINED LIBRARY (115 total sessions)
// ============================================
export const allMeditations: MeditationData[] = [
  ...breathingMeditations,
  ...mindfulnessMeditations,
  ...visualizationMeditations,
  ...stressReliefMeditations,
  ...sleepMeditations
]

// Export individual arrays for type-based access
export {
  breathingMeditations as breathing,
  mindfulnessMeditations as mindfulness,
  visualizationMeditations as visualization,
  stressReliefMeditations as stress_relief,
  sleepMeditations as sleep
}
